### ISSUE TITLE
Local Gamepad input

### ISSUE THREAD

**Issue by manglemix** [utahrobotics/usr-ws-2023#1]
**What must be done**
We need a node that can listen to a PS4 Controller, ideally Xbox or more as well, on Windows and Ubuntu, and will convert that input into messages. The content of these messages has yet to be determined.

**Existing 3rd party solutions**
There are no ROS 2 nodes that can do what exactly what we need, and these repositories have practically no stars. Here is one:
https://github.com/felipevanwinkle/ROS2-GamePad

There is most definitely a Python library that can get gamepad input in a cross-platform way however, but I have not tried to find one yet

**Existing internal solutions**
There was a node for ROS 1 that did this, and we did use it in usr_ws_2021, but it does not work with ROS 2

**Quirks or Specifics**
Making the solution work in multiple OS' and with multiple gamepads may be a bigger challenge than it seems. Spend more time finding libraries that do as much of the work for us

**Comment by manglemix** [comment]
For now, messages can contain two Vector2's (2D vectors), called `left_axis` and `right_axis`

**Comment by AGilsoul** [comment]
So for this, just to make sure I understand, do you want the node to create a publisher that will publish to the topic "movement_intent", or am I misunderstanding that?

**Comment by AGilsoul** [comment]
This was an accident I apologize, I meant to ask, with this, do you want the node to publish the message to the movement_intent topic?

**Comment by manglemix** [comment]
I have resolved the issue with the to-do column (glad you pointed that out). We will not deal with transform broadcasts here because that is for moving components to declare their current transform (If I am understanding the documentation correctly, you are referring to TF2 yes?), but this node should just broadcast the `movement_intent` topic so that listeners (that we have yet to write) can determine how that should be used to move the robot. So essentially, the transform broadcasts are a later step (but I doubt that we will be doing that).

**Comment by AGilsoul** [comment]
Yeah, that's the one I was referring to. But okay cool I understand now, thanks.

**Comment by AGilsoul** [comment]
Would we be able to use the Pygame library for this? It seems to have cross-platform support and I've been able to use it to get input from PS4 and Xbox controllers. I have found another smaller library, Inputs, that works on Windows and Linux, however, only Xbox controllers work on both. PS4 controllers are supported on Linux, but extra drivers are required for them to work with Windows

**Comment by manglemix** [comment]
Pygame is a pretty big dependency. It could be interesting to figure out how they do it. However, that is pretty overkill. Inputs sounds perfectly fine.

**Comment by manglemix** [comment]
@AGilsoul I have decided to update the requirements. We do not need to axes in the message, just two floats:
`drive` and `steering`.
These represent values from -1.0 to 1.0
The left axis' x and y values should correspond directly to this, and the right axis should be unused for now.

If you also have the time, I would suggest small checks for stick drift (ie. add minimum absolute value else 0)

**Comment by AGilsoul** [comment]
okay sounds good, so just the left joystick, and then add deadzones?

**Comment by manglemix** [comment]
That is exactly right

**Comment by AGilsoul** [comment]
Okay, I tried pushing the code to the local gamepad input branch, however it gets a runtime error on a job, saying it can't find a file that is included with it. I'm not sure what to do since it runs fine when I run it, and since it's not a warning I don't think I can just ignore it.

**Comment by manglemix** [comment]
I have updated the workflow to ignore that specific error (because pylint doesn't understand how ros2 works). The tests still fail because you have a few warnings about documentation, but that is fine because you only need to pass the tests when we merge branches together

**Comment by AGilsoul** [comment]
okay sounds good, thanks

**Comment by manglemix** [comment]
If you are done with the code, please change the status of the issue (in the project) to reviewing

**Comment by AGilsoul** [comment]
okay I'll do that once I commit the deadzone changes

**Comment by AGilsoul** [comment]
and you said to wait to comment everything until after the review right?

**Comment by manglemix** [comment]
yep

**Comment by manglemix** [comment]
@AGilsoul I have looked at the code and made a small simplification to how the main body of code is run
I was curious if you knew if `get_gamepad()` is a blocking call. If it isn't, and it returns an empty iterator if there are no events, you should use a [rate](https://docs.ros2.org/latest/api/rclpy/api/timers.html) class to limit the number of loops per second to a configurable number (hardcoded as a class variable is fine for now)

**Comment by AGilsoul** [comment]
@manglemix Oops I forgot I had doubles of the stuff in main, thanks. I'm not sure about the blocking call thing, but I will remove the while loop and add a timed callback so it is called repeatedly as you said.

**Comment by manglemix** [comment]
@AGilsoul Actually you should not do that. Keep the loop but add a sleep inside it using the rate class. Adding a callback triggered by rate can cause multiple calls to be active if `get_gamepad()` is blocking, which can use up memory and cause weird behavior

**Comment by manglemix** [comment]
Also add a line to log "Event received" inside the loop so that when we test it we can see if the call truly is blocking

**Comment by AGilsoul** [comment]
@manglemix Okay I've got the rate sleep working, however I've noticed that whenever I'm using the rate and moving the joystick around, there's a lot of delay (sometimes at least a second) between the joystick input and the publisher publishing the new input. This only happens when I have the rate sleep implemented, and even when I make the sleep time very small it still seems to have a considerable delay. I'm not sure if this is an issue with the inputs library or not, but I can't seem to fix it.

**Comment by manglemix** [comment]
Okay then you should remove rate

**Comment by AGilsoul** [comment]
Okay, so the only change then is just the logger?

**Comment by manglemix** [comment]
@AGilsoul Been trying to get an automated ROS 2 test to run on this branch, but it doesn't seem to work. The code nonetheless looks like it should work, so imma change the status to documenting.

**Comment by AGilsoul** [comment]
@manglemix sounds good, yeah I've been struggling with making the CMakeLists.txt and XML files correctly work with ROS, I'll try and get the documentation done tonight though.

**Comment by AGilsoul** [comment]
How much documentation is needed? I made another commit with some comments added but I'm not sure how much is needed.

**Comment by manglemix** [comment]
@AGilsoul Since this class is unlikely to be used in other classes, you do not need docstrings. Regular comments to just briefly describe what's going on is sufficient. The code all looks good now so good job! We will test this alongside the other code when they are ready

**Comment by manglemix** [comment]
@AGilsoul I've reopened this issue because I want the node to not crash if there is no controller connected. It would also be really good to be able to do hot-swapping of controllers. Meaning while the node is running, we can unplug the current controller and plug in another controller and it will still work

**Comment by AGilsoul** [comment]
Okay, I pushed the changes to the local-gamepad-input branch. I tested it without a controller plugged in, and with a controller plugged in, unplugging it, and plugging it back in and it seems to work.

**Comment by manglemix** [comment]
Nice job
