### ISSUE TITLE
Typos and Grammatical Errors in README

### ISSUE THREAD

**Issue by manglemix** [utahrobotics/usr-ws-2023#3]
**Describe the issue**
The README file in `main` has a few issues. If you are new to Git/GitHub and want some practice, this is the way! I've intentionally not created a branch for this, so you can make one yourself (remember, this repo will not let you commit to `main` directly)

**Comment by ash-01xor** [comment]
Can you assign me this issue

**Comment by manglemix** [comment]
@ash-01xor I'm sorry but collaboration in this repo is strictly limited to members only. This is not an open-source project

**Comment by ash-01xor** [comment]
Ohh okay got it

**Comment by manglemix** [comment]
Upgraded to #8
