### ISSUE TITLE
Basic Stepper Motor Controller

### ISSUE THREAD

**Issue by manglemix** [utahrobotics/usr-ws-2023#4]
**What must be done**
Any node that wants to move the robot will broadcast a `movement_intent` message with a `drive` and `steering` parameter. These values range from -1.0 to 1.0. The Stepper Motor Controller Node shall listen for these messages and send messages through GPIO to the actual stepper motor microcontroller. Movement of these motors _shall not_ persist if there are no messages (this is a task for the microcontroller). Since the stepper motors are responsible only for steering, the node will only look at the `steering` parameter.

**Existing 3rd party solutions**
At the time of writing, I have not done adequate research on what is needed.

**Existing internal solutions**
There is a stepper motor controller node in `usr_ws_2021/src/motors/scripts/steppers`, however, it delegated too much work to the microcontroller itself (which is difficult to debug), and remained silent if there were no changes, even if the motors should still be moving.

**Quirks or Specifics**
Working with GPIO and hardware is something most of you guys will not have dealt with. Feel free to research about it, but do not worry if you do not understand it. There should be other tasks to do in the meantime.

**Comment by manglemix** [comment]
I will try to move as much code as I can whenever I am free

**Comment by AGilsoul** [comment]
Do you know what type of stepper motor and microcontroller will be used?

**Comment by manglemix** [comment]
I do not know what is the exact name for either, but you can see how communication was done [here](https://github.com/utahrobotics/usr_ws_2021/blob/main/src/motors/scripts/steppers/serial_stepper_control.py). Questions relating to electrical components can be directed towards Daniel Glenn Robinson on Teams (he's the electrical team lead and he's pretty chill)

**Comment by AGilsoul** [comment]
Do you know what happened to motors/msg in the usr_ws_2021 repository? The stepper control from that uses a bunch of messages from it, however when I look at the .msg file inside the /msg folder, it is empty, so I can't find out what the stepper control file is actually doing and using the data for.

**Comment by manglemix** [comment]
Sorry for the late reply. The main branch is actually very old. Refer to the brushless-init or the odrive-fix branch

**Comment by manglemix** [comment]
We are ditching the stepper motor controllers in the final design in favor of skid steering
